### ISSUE TITLE
These lines don't compile anymore ...

### ISSUE THREAD

**Issue by hubertvolz** [spring-security-livelessons/oauth2#2]
Hi Josh and Rob,

Thanks for the great lessons about spring security, but these lines don't compile anymore. It would be great to have it fixed as this example is really helpful for people who watched your course.

Thanks, best regards and stay healthy!
 hubert

https://github.com/spring-security-livelessons/oauth2/blob/6502369a8e29eeeb07e1b50ca362465acca45539/resource-server/src/main/java/livelessons/SecurityConfig.java#L17

**Comment by rwinch** [comment]
Thanks for the ticket! This is now fixed via 998d5adbea54a24cbf71e4b101bcff8dd34b4dca
