### ISSUE TITLE
This class was removed ;-)

### ISSUE THREAD

**Issue by hubertvolz** [spring-security-livelessons/oauth2#3]
Hi Josh and Rob,

Josh deleted this class https://github.com/spring-projects/spring-security/issues/5734 ;-). So this doesn't compile anymore ;-).

best regards and stay healthy!
 hubert

https://github.com/spring-security-livelessons/oauth2/blob/6502369a8e29eeeb07e1b50ca362465acca45539/login/src/main/java/livelessons/LoginApplication.java#L27

**Comment by rwinch** [comment]
Thanks for the report! This was fixed via 998d5adbea54a24cbf71e4b101bcff8dd34b4dca
