### ISSUE TITLE
Not anymore in HttpSecurity

### ISSUE THREAD

**Issue by hubertvolz** [spring-security-livelessons/oauth2#4]
Hi Josh and Rob,

similar to the other issue I created: oauth2() does not exist anymore on HttpSecurity. As this example is general very helpful, it would be great to see it fixed.

Thanks, best regards and still stay healthy!
 hubert 

https://github.com/spring-security-livelessons/oauth2/blob/6502369a8e29eeeb07e1b50ca362465acca45539/login/src/main/java/livelessons/SecurityConfig.java#L13

**Comment by rwinch** [comment]
Thanks for the report! This is fixed via 998d5adbea54a24cbf71e4b101bcff8dd34b4dca
